# Generated by Django 6.0.5 on 2026-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empresa', models.CharField(max_length=12, unique=True, verbose_name='RUT de la Empresa')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre Fantasía')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Principal')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de Contacto')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección Principal')),
                ('codigo_sii', models.CharField(max_length=10, verbose_name='Código Actividad SII')),
                ('password', models.CharField(max_length=128)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario PYME',
                'verbose_name_plural': 'Usuarios PYME',
            },
        ),
    ]
