# Generated by Django 6.0.5 on 2026-05-12 17:54

import usuario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopyme',
            name='rut_empresa',
            field=models.CharField(max_length=12, unique=True, validators=[usuario.validators.validar_rut_chileno], verbose_name='RUT de la Empresa'),
        ),
    ]
