# Generated by Django 6.0.5 on 2026-05-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuariopyme_rut_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopyme',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Pyme', 'Empresa Cliente'), ('Bodeguero', 'Bodeguero')], default='Pyme', max_length=20),
        ),
    ]
